name: windows
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  Test-PSPerl:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: psperl -Setup
        run: .\psperl.ps1 -Setup
      - name: psperl -Init
        run: .\psperl.ps1 -Init
      - name: psperl -Available
        run: psperl -Available
